### ISSUE TITLE
Unable to get headers

### ISSUE THREAD

**Issue by KararTY** [devsnek/snekfetch#20]
Snekfetch version or commit hash: 76d9cbd

Explanation of issue:
I'm unable to get headers, like cookies. Only header I can actually get is content-type.

Code to reproduce:
```js
snek.post(url + '/login/app').send(details).then(res => {
console.log(res.headers['set-cookie'])
})
```
This previously worked in, again, version **3.2.9** as did #16 but not in 76d9cbd .

- Using snekfetch in electron (Assuming it's using **browser** because it detects it as such)

**Comment by devsnek** [comment]
this should be fixed after i merge the testing branch, i isolated the issue to a silly spec decision around how fetch works.

**Comment by KararTY** [comment]
Alright. Will wait for the merge. 👍

**Comment by devsnek** [comment]
closed in 58ca5a49ee4465702704c33380eabf2114cc4d44

**Comment by KararTY** [comment]
@devsnek Re-open.

58ca5a4
![img1](https://i.imgur.com/BPFpAYE.png "Still not working.")

Version 3.2.9
![img2](https://i.imgur.com/SIRdO02.png "Old version, still working.") 

Still not working.

**Comment by devsnek** [comment]
I can't reproduce

**Comment by KararTY** [comment]
Then it's probably an implementation issue:
https://github.com/FreeFrontiers/FreeFrontiers-App/blob/master/src/renderer.js#L847

Well? This worked with 3.2.9

**Comment by devsnek** [comment]
@kararty this might also be your issue https://stackoverflow.com/questions/43344819/reading-response-headers-with-fetch-api

the old version of snekfetch used XHR which doesn't have the same security restrictions as fetch, AND in electron it would have used node http, which has no security stuff
